# Generated by Django 5.0.4 on 2024-04-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mainuser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_fname', models.CharField(max_length=35)),
                ('user_lname', models.CharField(max_length=35)),
                ('user_mail', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=8)),
                ('user_dob', models.DateField()),
                ('user_phonenumber', models.BigIntegerField()),
            ],
        ),
    ]
