# Generated by Django 5.0.4 on 2024-04-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
