# Generated by Django 5.0.4 on 2024-04-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_app', '0002_alter_mainuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='mainuser',
            table='sm_app_mainuser',
        ),
    ]
