# Generated by Django 5.0.4 on 2024-04-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_app', '0003_alter_mainuser_user_id_alter_mainuser_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='user_mail',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
