# Generated by Django 5.0.4 on 2024-04-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_app', '0004_alter_mainuser_user_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='user_password',
            field=models.CharField(max_length=128),
        ),
    ]
