# Generated by Django 5.0.4 on 2024-04-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_app', '0005_alter_mainuser_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopOwner',
            fields=[
                ('o_id', models.AutoField(primary_key=True, serialize=False)),
                ('o_name', models.CharField(max_length=35)),
                ('o_mail', models.EmailField(max_length=254, unique=True)),
                ('o_password', models.CharField(max_length=128)),
                ('o_dob', models.DateField()),
                ('o_phonenumber', models.BigIntegerField()),
                ('o_address', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'sm_app_shopowner',
            },
        ),
    ]
