# Generated by Django 5.0.4 on 2024-04-11 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_app', '0006_shopowner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperMarket',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=50)),
                ('s_mail', models.EmailField(max_length=254, unique=True)),
                ('s_phonenumber', models.BigIntegerField()),
                ('s_type', models.CharField(max_length=100)),
                ('s_address', models.CharField(max_length=200)),
                ('s_opentime', models.TimeField()),
                ('s_closetime', models.TimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sm_app.shopowner')),
            ],
            options={
                'db_table': 'sm_app_supermarket',
            },
        ),
    ]
