# Generated by Django 5.0.4 on 2024-05-14 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_app', '0007_supermarket'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sm_app.supermarket')),
            ],
            options={
                'db_table': 'sm_app_categories',
            },
        ),
    ]
