# Generated by Django 5.0.4 on 2024-05-14 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_app', '0008_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('quntity', models.IntegerField(default=1, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sm_app.categories')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sm_app.supermarket')),
            ],
            options={
                'db_table': 'sm_app_product',
            },
        ),
    ]
