# Generated by Django 5.0.4 on 2024-05-16 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sm_app', '0010_alter_categories_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quntity',
        ),
    ]
