# Generated by Django 5.0.4 on 2024-05-16 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_app', '0011_remove_product_quntity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_name',
            field=models.CharField(max_length=100),
        ),
    ]
