# Generated by Django 5.0.4 on 2024-05-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_app', '0013_alter_product_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
