# Generated by Django 5.0.4 on 2024-05-18 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_app', '0014_product_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sm_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sm_app.mainuser')),
            ],
            options={
                'db_table': 'sm_app_orders',
            },
        ),
    ]
