# Generated by Django 5.0.4 on 2024-05-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_app', '0015_mainuser_is_active_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
