# Generated by Django 5.0.4 on 2024-05-20 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_app', '0017_product_quantity_delete_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.FloatField()),
                ('shop_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sm_app.shopowner')),
                ('supermarket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sm_app.supermarket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sm_app.mainuser')),
            ],
            options={
                'db_table': 'sm_app_Order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sm_app.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sm_app.product')),
            ],
            options={
                'db_table': 'sm_app_OrderItem',
            },
        ),
    ]
