# Generated by Django 5.0.4 on 2024-05-22 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_app', '0020_payment_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('update_desc', models.CharField(max_length=500)),
                ('update_timestamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sm_app.order')),
            ],
            options={
                'db_table': 'sm_app_OrderUpdate',
            },
        ),
    ]
