# Generated by Django 5.0.4 on 2024-05-22 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sm_app', '0021_remove_payment_transaction_id_order_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.DeleteModel(
            name='OrderUpdate',
        ),
    ]
