# Generated by Django 5.0.4 on 2024-05-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_app', '0024_order_payment_status_orderupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
    ]
