# Generated by Django 5.0.4 on 2024-05-29 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_app', '0025_alter_payment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='supermarket',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='supermarket',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
