# Generated by Django 5.0.4 on 2024-05-31 07:15

import sm_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_app', '0028_alter_supermarket_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supermarket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=sm_app.models.supermarket_image_path),
        ),
    ]
