# Generated by Django 5.0.4 on 2024-05-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_app', '0029_alter_supermarket_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
