# Generated by Django 5.0.4 on 2024-05-31 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sm_app', '0031_remove_categories_category_image_categories_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='image',
            new_name='category_image',
        ),
    ]
