# Generated by Django 5.0.4 on 2024-05-31 16:36

import sm_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_app', '0033_alter_categories_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=sm_app.models.supermarket_image_path),
        ),
        migrations.AlterField(
            model_name='categories',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
