# Generated by Django 5.0.4 on 2024-05-31 18:21

import sm_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_app', '0035_remove_categories_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to=sm_app.models.supermarket_image_path),
        ),
    ]
