# Generated by Django 5.0.4 on 2024-06-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_app', '0036_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='template_name',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
