# Generated by Django 5.0.4 on 2024-06-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_app', '0037_categories_template_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='template_name',
            field=models.CharField(default='checkboxproducts.html', max_length=100),
        ),
    ]
