# Generated by Django 5.0.4 on 2024-06-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_app', '0038_alter_categories_template_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PLACED', 'Placed'), ('PACKED', 'Packed'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PLACED', max_length=50),
        ),
        migrations.AlterModelTable(
            name='order',
            table='sm_app_order',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='sm_app_orderitem',
        ),
    ]
