# Generated by Django 5.0.4 on 2024-06-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_app', '0041_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PLACED', 'Placed'), ('PACKED', 'Packed'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=50),
        ),
    ]
