# Generated by Django 5.0.4 on 2024-06-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_app', '0043_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
