# Generated by Django 5.0.4 on 2024-06-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_app', '0044_order_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PLACED', 'Placed'), ('ORDERCOMMITTED', 'Order Committed'), ('PACKED', 'Packed'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PLACED', max_length=50),
        ),
    ]
