# Generated by Django 5.0.4 on 2024-06-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_app', '0047_deliveryboy_order_delivery_boy'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_deliverydec',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='order_deliverysoc',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
