# Generated by Django 5.0.4 on 2024-06-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_app', '0048_order_order_deliverydec_order_order_deliverysoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='extemplate_name',
            field=models.CharField(default='existing_products.html', max_length=100),
        ),
    ]
