# Generated by Django 5.0.4 on 2024-06-17 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_app', '0050_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
