# Generated by Django 3.1.8 on 2024-06-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_app', '0051_order_delivered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_staus',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
