# Generated by Django 3.1.8 on 2024-07-03 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sm_app', '0052_auto_20240628_1338'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedback',
            table='Feedback',
        ),
    ]
