"""
Django settings for smartmart project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from django.contrib import messages
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1+z@wm_+u$1@zno_%t2$o9fn^12zq1aoq0sg2qctskd0z2#3pe'

import os

# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# # Ensure the media folder exists
# if not os.path.exists(MEDIA_ROOT):
#     os.makedirs(MEDIA_ROOT)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True #firstly its is true i changed it at payments time
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'teamsmartmart@gmail.com'
EMAIL_HOST_PASSWORD = 'ulbp ryji ygli mqhm'



# settings.py

# Use database-backed sessions
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.your-email-provider.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@example.com'
# EMAIL_HOST_PASSWORD = 'your-email-password'
# DEFAULT_FROM_EMAIL = 'your-email@example.com'

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sm_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]

ROOT_URLCONF = 'smartmart.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'smartmart.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'smartmart_db',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': '127.0.0.1',  # or the hostname where your MySQL server is running
        'PORT': '3306',      # or the port on which your MySQL server is listening
    
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# settings.py
GOOGLE_MAPS_API_KEY = 'AIzaSyC1_C2hK2og3x2ZHq2v3ZHMgpmPFBgU3XI'
# settings.py

# GOOGLE_MAPS_API_KEY = 'your_api_key_here'

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL='/images/'

STATICFILES_DIRS=[
    os.path.join(BASE_DIR, 'static')
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# # settings.py
# CSRF_TRUSTED_ORIGINS = [
#     'http://localhost',
#     'http://127.0.0.1',
#     "http://127.0.0.1:8000",
# ]
CSRF_COOKIE_SAMESITE = 'Strict'  # Or 'Lax' depending on your requirements

# DEBUG = False
ALLOWED_HOSTS = []
# ALLOWED_HOSTS = ['localhost', '127.0.0.1', '127.0.01:8000', '*.razorpay.com']


# settings.py

# PAYTM_MERCHANT_KEY = 'L5ntx50epDr8%fzE'
# PAYTM_MERCHANT_ID = 'pjzBPJ75757868758377'
# PAYTM_WEBSITE = 'WEBSTAGING'
# PAYTM_CHANNEL_ID = 'WEB'
# PAYTM_INDUSTRY_TYPE_ID = 'Retail'
# PAYTM_CALLBACK_URL = 'http://127.0.0.1:8000/paytm/response/'
# PAYTM_MERCHANT_ID = 'pjzBPJ75757868758377'
# PAYTM_MERCHANT_KEY = 'L5ntx50epDr8%fzE'
# PAYTM_WEBSITE = 'WEBSTAGING'
# PAYTM_CHANNEL_ID = 'WEB'
# PAYTM_INDUSTRY_TYPE_ID = 'Retail'
# PAYTM_CALLBACK_URL = 'http://127.0.0.1:8000/payment/callback/'


# PAYTM_MERCHANT_KEY = 'your_merchant_key'
# PAYTM_MERCHANT_ID = 'your_merchant_id'
# PAYTM_WEBSITE = 'WEBSTAGING'  # Use 'WEBSTAGING' for testing and 'WEB' for production
# PAYTM_CHANNEL_ID = 'WEB'
# PAYTM_INDUSTRY_TYPE_ID = 'Retail'
# PAYTM_CALLBACK_URL = 'http://127.0.0.1:8000/paytm/response/'  # Update to your callback URL

# settings.py
# razorpay_id = 'rzp_test_NGNJnABSHq3UNx'
# razorpay_account_id = '6VhZg6BWX167TJEE4s50Di2A'

# settings.py
RAZORPAY_ID = 'rzp_test_JtRCVwvuv0LD5v'
RAZORPAY_ACCOUNT_ID = 'itNw7BFj17bBMXv456uI6OlI'


# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Fast2SMS settings
FAST2SMS_API_KEY = 'BQzxhu6C2Rin7dojUVLSPT8clZHM5FDvkeIAwJKtrOXfWgm9Eys7zCxiTjYRua4JUGMNmrI19cZbl2VQ'


# # Define your custom media path
# CUSTOM_MEDIA_PATH = '/path/to/your/custom/media/'

# # Set the media root
# MEDIA_ROOT = os.path.join(BASE_DIR, CUSTOM_MEDIA_PATH)

# # Set the media URL
# MEDIA_URL = '/media/'

import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Define your custom media path
CUSTOM_MEDIA_PATH = 'media/'

# Set the media root
MEDIA_ROOT = os.path.join(BASE_DIR, CUSTOM_MEDIA_PATH)

# Set the media URL
MEDIA_URL = '/media/'




# Set session to expire when the browser is closed
SESSION_EXPIRE_AT_BROWSER_CLOSE = True


LOGIN_URL = '/login/'  # The URL where users are redirected to log in

